apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: appuio-spring-boot-ex
  name: appuio-spring-boot-ex
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: appuio-spring-boot-ex
  name: java-centos-openjdk11-jdk
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: fabric8/java-centos-openjdk11-jdk
    from:
      kind: DockerImage
      name: fabric8/java-centos-openjdk11-jdk
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source